const SITES=[
 {id:'ada-main',name:'ADA MAIN',url:'https://andreas-digital-agency.vercel.app'},
 {id:'ada-web',name:'ADA WEB',url:'https://ada-web-division.vercel.app'},
 {id:'ada-tech',name:'ADA TECH',url:'https://ada-tech-division.vercel.app'},
 {id:'portfolio',name:'PORTFOLIO',url:'https://kudumo-portfolio.vercel.app'}
];
const $=id=>document.getElementById(id);let state={checks:[],summary:null,generatedAt:null};
const histories=JSON.parse(localStorage.getItem('adaSentinelHistory')||'{}');SITES.forEach(s=>histories[s.id]=Array.isArray(histories[s.id])?histories[s.id].slice(-30):[]);
function esc(v){return String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function time(){return new Date().toLocaleTimeString('en-GB',{hour12:false})}setInterval(()=>$('sysTime').textContent=time(),1000);$('sysTime').textContent=time();
function spark(values,color='var(--green)'){const arr=values.length?values:[0,0,0,0,0];const max=Math.max(...arr,1),min=Math.min(...arr,0),w=100,h=25;const pts=arr.map((v,i)=>`${(i/(Math.max(arr.length-1,1))*w).toFixed(1)},${(h-((v-min)/(Math.max(max-min,1))*h)).toFixed(1)}`).join(' ');return `<svg viewBox="0 0 100 25" preserveAspectRatio="none"><polyline style="stroke:${color}" points="${pts}"/></svg>`}
function byId(id){return state.checks.find(x=>x.id===id)}
function fleetCard(site){const c=byId(site.id);const ok=c?.online;const h=histories[site.id]||[];const warn=c?c.security.filter(x=>!x.ok).length:0;return `<article class="siteCard"><div class="siteHead"><b>${site.name}</b><span class="badge ${ok?'':'warn'}">${c?(ok?'ONLINE':'OFFLINE'):'SCANNING'}</span></div><div class="siteUrl">${site.url.replace('https://','')}</div><div class="siteBody"><div class="gauge" style="--v:${c?.healthScore||0}"><div class="inner"><strong>${c?c.healthScore.toFixed(0)+'%':'--'}</strong><small>HEALTH SCORE</small></div></div><div class="siteFacts"><div class="fact"><span>Status</span><b>${c?.statusCode||'--'}</b></div><div class="fact"><span>Response</span><b>${c?c.responseMs+'ms':'--'}</b></div><div class="fact"><span>Warnings</span><b>${c?warn:'--'}</b></div><div class="fact"><span>Last Scan</span><b>${c?new Date(c.checkedAt).toLocaleTimeString('en-GB',{hour12:false}):'--'}</b></div></div></div><div class="spark">${spark(h.map(x=>x.ms))}</div></article>`}
function buildAlerts(){const out=[];state.checks.forEach(c=>{const s=SITES.find(x=>x.id===c.id);if(!c.online)out.push({sev:'critical',title:`${s.name} is offline`,detail:c.error||`HTTP ${c.statusCode}`});if(c.responseMs>1200)out.push({sev:'warning',title:`High response time`,detail:`${s.name} · ${c.responseMs}ms`});c.security.filter(x=>!x.ok).forEach(x=>out.push({sev:'warning',title:`${x.label} missing`,detail:`${s.name} · security header`}));if(!c.robots?.ok)out.push({sev:'info',title:'robots.txt unavailable',detail:`${s.name} · HTTP ${c.robots?.status||0}`});if(!c.sitemap?.ok)out.push({sev:'info',title:'sitemap.xml unavailable',detail:`${s.name} · HTTP ${c.sitemap?.status||0}`});if(c.certificate?.daysRemaining!==null&&c.certificate.daysRemaining<30)out.push({sev:'warning',title:'TLS certificate window',detail:`${s.name} · ${c.certificate.daysRemaining} days remaining`});});return out.slice(0,8)}
function renderAlerts(alerts){$('alerts').innerHTML=alerts.length?alerts.map((a,i)=>`<div class="alertRow"><time>${new Date(state.generatedAt).toLocaleTimeString('en-GB',{hour12:false})}</time><div><strong>${esc(a.title)}</strong><small>${esc(a.detail)}</small></div><span class="severity ${a.sev}">${a.sev.toUpperCase()}</span></div>`).join(''):`<div class="alertRow"><time>${time()}</time><div><strong>All live sensors clear</strong><small>No current HTTP or baseline security findings</small></div><span class="severity info">INFO</span></div>`}
function coreStats(){const avgSec=state.summary?.avgSecurity||0;const allHttps=state.checks.every(c=>c.security?.find(x=>x.label==='HTTPS')?.ok);const certGood=state.checks.every(c=>c.certificate?.daysRemaining===null||c.certificate.daysRemaining>14);$('coreLeft').innerHTML=`<div class="coreStat"><b>HTTPS TRANSPORT</b><span class="${allHttps?'':'warn'}">${allHttps?'ACTIVE':'ATTENTION'}</span></div><div class="coreStat"><b>HEADER DEFENSE</b><span class="${avgSec>=80?'':'warn'}">${avgSec>=80?'HARDENED':'PARTIAL'}</span></div><div class="coreStat"><b>AVAILABILITY MONITOR</b><span>ACTIVE</span></div>`;$('coreRight').innerHTML=`<div class="coreStat"><b>TLS CERTIFICATE WATCH</b><span class="${certGood?'':'warn'}">${certGood?'ACTIVE':'ATTENTION'}</span></div><div class="coreStat"><b>ROBOTS / SITEMAP</b><span>MONITORING</span></div><div class="coreStat"><b>INCIDENT DETECTION</b><span>ACTIVE</span></div>`}
function aggregateHistory(){const samples=[];for(let i=0;i<30;i++){const vals=SITES.map(s=>histories[s.id]?.[histories[s.id].length-30+i]).filter(Boolean);if(vals.length)samples.push(Math.round(vals.reduce((a,b)=>a+b.ms,0)/vals.length))}return samples}
function telemetry(){const s=state.summary||{};const ag=aggregateHistory();const slow=Math.max(...state.checks.map(c=>c.responseMs),0);const metrics=[['AVG RESPONSE TIME',`${s.avgResponseMs??'--'}ms`,ag,'#25dfff'],['SLOWEST ENDPOINT',`${slow||'--'}ms`,SITES.map(x=>histories[x.id].at(-1)?.ms||0),'#ffb72d'],['FLEET HEALTH',`${s.avgHealth??'--'}%`,ag.map(v=>Math.max(0,100-Math.min(30,Math.round(v/100)))),'#36f29a'],['SECURITY COVERAGE',`${s.avgSecurity??'--'}%`,state.checks.map(c=>c.securityScore),'#36f29a']];$('telemetry').innerHTML=metrics.map(m=>`<div class="metricRow"><div><div class="label">${m[0]}</div><strong>${m[1]}</strong></div><div class="teleSpark">${spark(m[2],m[3])}</div></div>`).join('')}
function production(){const s=state.summary||{};const success=s.online||0,failed=(s.total||4)-success;$('prodDonut').style.setProperty('--v',Math.round(success/(s.total||4)*100));$('prodStats').innerHTML=`<div class="ds"><span>● REACHABLE</span><b class="ok">${success}</b></div><div class="ds"><span>● FAILED</span><b style="color:var(--red)">${failed}</b></div><div class="ds"><span>● SENSOR CYCLE</span><b>60s</b></div>`}
function errorFeed(alerts){const rows=alerts.slice(0,5);$('errorFeed').innerHTML=rows.length?rows.map(a=>`<div class="errRow"><time>${new Date(state.generatedAt).toLocaleTimeString('en-GB',{hour12:false})}</time><span class="code">${a.sev==='critical'?'ERR':a.sev==='warning'?'WARN':'INFO'}</span><span class="route">${esc(a.title)}</span><span>${esc(a.detail.split('·')[0])}</span></div>`).join(''):`<div class="errRow"><time>${time()}</time><span class="code" style="color:var(--green)">OK</span><span class="route">No current findings</span><span>Fleet</span></div>`}
function monitoring(){ $('monitorList').innerHTML=state.checks.map(c=>{const s=SITES.find(x=>x.id===c.id);return `<div class="ml"><span>${s.name}</span><b>${c.responseMs}ms</b><span style="color:${c.online?'var(--green)':'var(--red)'}">${c.online?'HEALTHY':'DOWN'}</span></div>`}).join('')}
function security(){const s=state.summary||{};$('secDonut').style.setProperty('--v',s.avgSecurity||0);$('secScore').textContent=(s.avgSecurity??'--')+'%';const high=state.checks.reduce((n,c)=>n+c.security.filter(x=>!x.ok&&['CSP','X-Frame-Options'].includes(x.label)).length,0);const med=state.checks.reduce((n,c)=>n+c.security.filter(x=>!x.ok&&!['CSP','X-Frame-Options'].includes(x.label)).length,0);$('secureFacts').innerHTML=`<div class="sf"><span>OFFLINE / CRITICAL</span><b>${s.critical??'--'}</b></div><div class="sf"><span>HIGH-RISK HEADER GAPS</span><b style="color:${high?'var(--amber)':'var(--green)'}">${high}</b></div><div class="sf"><span>OTHER HEADER GAPS</span><b>${med}</b></div><div class="sf"><span>BASELINE COVERAGE</span><b>${s.avgSecurity??'--'}%</b></div>`}
function feed(alerts){const parts=[`Health scan completed · ${state.summary?.online||0}/${state.summary?.total||4} online`,`Average response · ${state.summary?.avgResponseMs||0}ms`,`Security coverage · ${state.summary?.avgSecurity||0}%`,...alerts.slice(0,4).map(a=>a.title)];$('feedMove').innerHTML=[...parts,...parts].map(x=>`<span>${esc(x)}</span>`).join('')}
function render(){const s=state.summary||{};$('fleet').innerHTML=SITES.map(fleetCard).join('');$('overallGauge').style.setProperty('--v',s.avgHealth||0);$('overallScore').textContent=(s.avgHealth??'--')+'%';$('onlineCount').textContent=s.online??'--';$('criticalCount').textContent=s.critical??'--';$('warningCount').textContent=s.warnings??'--';$('avgLatency').textContent=s.avgResponseMs??'--';$('networkStatus').textContent=s.online===s.total?'ONLINE':'DEGRADED';$('networkStatus').className=s.online===s.total?'good':'warn';$('sensorStatus').textContent=`${state.checks.length}/${s.total||4} ACTIVE`;$('threatLevel').textContent=s.critical?'HIGH':s.securityGaps>0?'ELEVATED':'LOW';$('threatLevel').className=s.critical?'warn':s.securityGaps>0?'warn':'good';$('coreState').textContent=s.critical?'DEGRADED':'OPERATIONAL';$('coreState').style.color=s.critical?'var(--red)':'var(--green)';const alerts=buildAlerts();renderAlerts(alerts);coreStats();telemetry();production();errorFeed(alerts);monitoring();security();feed(alerts);$('lastScan').textContent=`LIVE DATA ONLY · last sensor sweep ${new Date(state.generatedAt).toLocaleString()} · source: ${state.source}`}
async function scan(){document.body.classList.add('loading');try{const r=await fetch('/api/health',{cache:'no-store'});if(!r.ok)throw new Error(`Monitor HTTP ${r.status}`);const d=await r.json();state=d;d.checks.forEach(c=>{histories[c.id].push({t:d.generatedAt,ms:c.responseMs,health:c.healthScore,sec:c.securityScore});histories[c.id]=histories[c.id].slice(-30)});localStorage.setItem('adaSentinelHistory',JSON.stringify(histories));render()}catch(e){$('networkStatus').textContent='MONITOR ERROR';$('networkStatus').className='warn';$('coreState').textContent='DEGRADED';$('alerts').innerHTML=`<div class="alertRow"><time>${time()}</time><div><strong>Monitor API error</strong><small>${esc(e.message)}</small></div><span class="severity critical">CRITICAL</span></div>`}finally{document.body.classList.remove('loading')}}
scan();setInterval(scan,60000);