const SITES=[
 {id:'ada-main',name:'ADA MAIN',url:'https://andreas-digital-agency.vercel.app'},
 {id:'ada-web',name:'ADA WEB',url:'https://ada-web-division.vercel.app'},
 {id:'ada-tech',name:'ADA TECH',url:'https://ada-tech-division.vercel.app'},
 {id:'portfolio',name:'PORTFOLIO',url:'https://kudumo-portfolio.vercel.app'}
];
const $=id=>document.getElementById(id);let state={checks:[],summary:null,generatedAt:null};
const histories=JSON.parse(localStorage.getItem('adaSentinelHistory')||'{}');SITES.forEach(s=>histories[s.id]=Array.isArray(histories[s.id])?histories[s.id].slice(-30):[]);
function esc(v){return String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function time(){return new Date().toLocaleTimeString('en-GB',{hour12:false})}setInterval(()=>$('sysTime').textContent=time(),1000);$('sysTime').textContent=time();
function spark(values,color='var(--green)'){const arr=values.length?values:[0,0,0,0,0];const max=Math.max(...arr,1),min=Math.min(...arr,0),w=100,h=25;const pts=arr.map((v,i)=>`${(i/(Math.max(arr.length-1,1))*w).toFixed(1)},${(h-((v-min)/(Math.max(max-min,1))*h)).toFixed(1)}`).join(' ');return `<svg viewBox="0 0 100 25" preserveAspectRatio="none"><polyline style="stroke:${color}" points="${pts}"/></svg>`}
function byId(id){return state.checks.find(x=>x.id===id)}
function fleetCard(site){const c=byId(site.id);const ok=c?.online;const h=histories[site.id]||[];const warn=c?c.security.filter(x=>!x.ok).length:0;return `<article class="siteCard"><div class="siteHead"><b>${site.name}</b><span class="badge ${ok?'':'warn'}">${c?(ok?'ONLINE':'OFFLINE'):'SCANNING'}</span></div><div class="siteUrl">${site.url.replace('https://','')}</div><div class="siteBody"><div class="gauge" style="--v:${c?.healthScore||0}"><div class="inner"><strong>${c?c.healthScore.toFixed(0)+'%':'--'}</strong><small>HEALTH SCORE</small></div></div><div class="siteFacts"><div class="fact"><span>Status</span><b>${c?.statusCode||'--'}</b></div><div class="fact"><span>Response</span><b>${c?c.responseMs+'ms':'--'}</b></div><div class="fact"><span>Warnings</span><b>${c?warn:'--'}</b></div><div class="fact"><span>Last Scan</span><b>${c?new Date(c.checkedAt).toLocaleTimeString('en-GB',{hour12:false}):'--'}</b></div></div></div><div class="spark">${spark(h.map(x=>x.ms))}</div></article>`}
function buildAlerts(){const out=[];state.checks.forEach(c=>{const s=SITES.find(x=>x.id===c.id);if(!c.online)out.push({sev:'critical',title:`${s.name} is offline`,detail:c.error||`HTTP ${c.statusCode}`});if(c.responseMs>1200)out.push({sev:'warning',title:`High response time`,detail:`${s.name} · ${c.responseMs}ms`});c.security.filter(x=>!x.ok).forEach(x=>out.push({sev:'warning',title:`${x.label} missing`,detail:`${s.name} · security header`}));if(!c.robots?.ok)out.push({sev:'info',title:'robots.txt unavailable',detail:`${s.name} · HTTP ${c.robots?.status||0}`});if(!c.sitemap?.ok)out.push({sev:'info',title:'sitemap.xml unavailable',detail:`${s.name} · HTTP ${c.sitemap?.status||0}`});if(c.certificate?.daysRemaining!==null&&c.certificate.daysRemaining<30)out.push({sev:'warning',title:'TLS certificate window',detail:`${s.name} · ${c.certificate.daysRemaining} days remaining`});});return out.slice(0,8)}
function renderAlerts(alerts){$('alerts').innerHTML=alerts.length?alerts.map((a,i)=>`<div class="alertRow"><time>${new Date(state.generatedAt).toLocaleTimeString('en-GB',{hour12:false})}</time><div><strong>${esc(a.title)}</strong><small>${esc(a.detail)}</small></div><span class="severity ${a.sev}">${a.sev.toUpperCase()}</span></div>`).join(''):`<div class="alertRow"><time>${time()}</time><div><strong>All live sensors clear</strong><small>No current HTTP or baseline security findings</small></div><span class="severity info">INFO</span></div>`}
function coreStats(){const avgSec=state.summary?.avgSecurity||0;const allHttps=state.checks.every(c=>c.security?.find(x=>x.label==='HTTPS')?.ok);const certGood=state.checks.every(c=>c.certificate?.daysRemaining===null||c.certificate.daysRemaining>14);$('coreLeft').innerHTML=`<div class="coreStat"><b>HTTPS TRANSPORT</b><span class="${allHttps?'':'warn'}">${allHttps?'ACTIVE':'ATTENTION'}</span></div><div class="coreStat"><b>HEADER DEFENSE</b><span class="${avgSec>=80?'':'warn'}">${avgSec>=80?'HARDENED':'PARTIAL'}</span></div><div class="coreStat"><b>AVAILABILITY MONITOR</b><span>ACTIVE</span></div>`;$('coreRight').innerHTML=`<div class="coreStat"><b>TLS CERTIFICATE WATCH</b><span class="${certGood?'':'warn'}">${certGood?'ACTIVE':'ATTENTION'}</span></div><div class="coreStat"><b>ROBOTS / SITEMAP</b><span>MONITORING</span></div><div class="coreStat"><b>INCIDENT DETECTION</b><span>ACTIVE</span></div>`}
function aggregateHistory(){const samples=[];for(let i=0;i<30;i++){const vals=SITES.map(s=>histories[s.id]?.[histories[s.id].length-30+i]).filter(Boolean);if(vals.length)samples.push(Math.round(vals.reduce((a,b)=>a+b.ms,0)/vals.length))}return samples}
function telemetry(){const s=state.summary||{};const ag=aggregateHistory();const slow=Math.max(...state.checks.map(c=>c.responseMs),0);const metrics=[['AVG RESPONSE TIME',`${s.avgResponseMs??'--'}ms`,ag,'#25dfff'],['SLOWEST ENDPOINT',`${slow||'--'}ms`,SITES.map(x=>histories[x.id].at(-1)?.ms||0),'#ffb72d'],['FLEET HEALTH',`${s.avgHealth??'--'}%`,ag.map(v=>Math.max(0,100-Math.min(30,Math.round(v/100)))),'#36f29a'],['SECURITY COVERAGE',`${s.avgSecurity??'--'}%`,state.checks.map(c=>c.securityScore),'#36f29a']];$('telemetry').innerHTML=metrics.map(m=>`<div class="metricRow"><div><div class="label">${m[0]}</div><strong>${m[1]}</strong></div><div class="teleSpark">${spark(m[2],m[3])}</div></div>`).join('')}
function production(){const s=state.summary||{};const success=s.online||0,failed=(s.total||4)-success;$('prodDonut').style.setProperty('--v',Math.round(success/(s.total||4)*100));$('prodStats').innerHTML=`<div class="ds"><span>● REACHABLE</span><b class="ok">${success}</b></div><div class="ds"><span>● FAILED</span><b style="color:var(--red)">${failed}</b></div><div class="ds"><span>● SENSOR CYCLE</span><b>60s</b></div>`}
function errorFeed(alerts){const rows=alerts.slice(0,5);$('errorFeed').innerHTML=rows.length?rows.map(a=>`<div class="errRow"><time>${new Date(state.generatedAt).toLocaleTimeString('en-GB',{hour12:false})}</time><span class="code">${a.sev==='critical'?'ERR':a.sev==='warning'?'WARN':'INFO'}</span><span class="route">${esc(a.title)}</span><span>${esc(a.detail.split('·')[0])}</span></div>`).join(''):`<div class="errRow"><time>${time()}</time><span class="code" style="color:var(--green)">OK</span><span class="route">No current findings</span><span>Fleet</span></div>`}
function monitoring(){ $('monitorList').innerHTML=state.checks.map(c=>{const s=SITES.find(x=>x.id===c.id);return `<div class="ml"><span>${s.name}</span><b>${c.responseMs}ms</b><span style="color:${c.online?'var(--green)':'var(--red)'}">${c.online?'HEALTHY':'DOWN'}</span></div>`}).join('')}
function security(){const s=state.summary||{};$('secDonut').style.setProperty('--v',s.avgSecurity||0);$('secScore').textContent=(s.avgSecurity??'--')+'%';const high=state.checks.reduce((n,c)=>n+c.security.filter(x=>!x.ok&&['CSP','X-Frame-Options'].includes(x.label)).length,0);const med=state.checks.reduce((n,c)=>n+c.security.filter(x=>!x.ok&&!['CSP','X-Frame-Options'].includes(x.label)).length,0);$('secureFacts').innerHTML=`<div class="sf"><span>OFFLINE / CRITICAL</span><b>${s.critical??'--'}</b></div><div class="sf"><span>HIGH-RISK HEADER GAPS</span><b style="color:${high?'var(--amber)':'var(--green)'}">${high}</b></div><div class="sf"><span>OTHER HEADER GAPS</span><b>${med}</b></div><div class="sf"><span>BASELINE COVERAGE</span><b>${s.avgSecurity??'--'}%</b></div>`}
function feed(alerts){const parts=[`Health scan completed · ${state.summary?.online||0}/${state.summary?.total||4} online`,`Average response · ${state.summary?.avgResponseMs||0}ms`,`Security coverage · ${state.summary?.avgSecurity||0}%`,...alerts.slice(0,4).map(a=>a.title)];$('feedMove').innerHTML=[...parts,...parts].map(x=>`<span>${esc(x)}</span>`).join('')}
function render(){const s=state.summary||{};$('fleet').innerHTML=SITES.map(fleetCard).join('');$('overallGauge').style.setProperty('--v',s.avgHealth||0);$('overallScore').textContent=(s.avgHealth??'--')+'%';$('onlineCount').textContent=s.online??'--';$('criticalCount').textContent=s.critical??'--';$('warningCount').textContent=s.warnings??'--';$('avgLatency').textContent=s.avgResponseMs??'--';$('networkStatus').textContent=s.online===s.total?'ONLINE':'DEGRADED';$('networkStatus').className=s.online===s.total?'good':'warn';$('sensorStatus').textContent=`${state.checks.length}/${s.total||4} ACTIVE`;$('threatLevel').textContent=s.critical?'HIGH':s.securityGaps>0?'ELEVATED':'LOW';$('threatLevel').className=s.critical?'warn':s.securityGaps>0?'warn':'good';$('coreState').textContent=s.critical?'DEGRADED':'OPERATIONAL';$('coreState').style.color=s.critical?'var(--red)':'var(--green)';const alerts=buildAlerts();renderAlerts(alerts);coreStats();telemetry();production();errorFeed(alerts);monitoring();security();feed(alerts);$('lastScan').textContent=`LIVE DATA ONLY · last sensor sweep ${new Date(state.generatedAt).toLocaleString()} · source: ${state.source}`}
async function scan(){document.body.classList.add('loading');try{const r=await fetch('/api/health',{cache:'no-store'});if(!r.ok)throw new Error(`Monitor HTTP ${r.status}`);const d=await r.json();state=d;d.checks.forEach(c=>{histories[c.id].push({t:d.generatedAt,ms:c.responseMs,health:c.healthScore,sec:c.securityScore});histories[c.id]=histories[c.id].slice(-30)});localStorage.setItem('adaSentinelHistory',JSON.stringify(histories));render();applyView(activeView,false)}catch(e){$('networkStatus').textContent='MONITOR ERROR';$('networkStatus').className='warn';$('coreState').textContent='DEGRADED';$('alerts').innerHTML=`<div class="alertRow"><time>${time()}</time><div><strong>Monitor API error</strong><small>${esc(e.message)}</small></div><span class="severity critical">CRITICAL</span></div>`}finally{document.body.classList.remove('loading')}}

let activeView='overview';
const NAV_KEYS=['overview','websites','security','monitoring','deployments','errors','reports','settings'];
const VIEW_META={
 overview:['COMMAND OVERVIEW','Full live command-centre view across all connected ADA platforms.'],
 websites:['WEBSITE FLEET','Live health, HTTP status, response time and recent scan history for every connected platform.'],
 security:['SECURITY COMMAND','Baseline browser-security headers, HTTPS transport and TLS certificate watch.'],
 monitoring:['REAL-TIME MONITORING','Response-time telemetry and live endpoint reachability from the current sensor cycle.'],
 deployments:['PRODUCTION STATUS','Current production endpoint reachability. Vercel release-history integration comes next.'],
 errors:['LOGS & ERRORS','Current live findings generated from HTTP, performance, sitemap, robots and security checks.'],
 reports:['SYSTEM REPORTS','A truthful summary generated from the latest Sentinel sensor sweep.'],
 settings:['SENTINEL SETTINGS','Current monitor configuration and connected platform inventory.']
};
function installNavigationStyles(){if(document.getElementById('sentinelNavStyles'))return;const style=document.createElement('style');style.id='sentinelNavStyles';style.textContent=`.viewContext{padding:12px 15px;display:none;align-items:center;justify-content:space-between;gap:18px;min-height:58px}.viewContext.show{display:flex}.viewContext .vcK{font-size:7px;color:#5e91a4;letter-spacing:.15em}.viewContext h2{font-size:15px;margin:4px 0 0;letter-spacing:.05em;color:#dff8ff}.viewContext p{font-size:7px;color:#75a0b1;margin:0;max-width:700px;line-height:1.5}.viewContext .vcLive{font-size:7px;color:var(--green);white-space:nowrap}.viewContext .vcLive:before{content:'●';margin-right:6px;text-shadow:0 0 8px var(--green)}.focusPanel{padding:16px}.focusGrid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.focusStat{border:1px solid #0b4e63;background:#07131c;padding:13px;min-height:92px}.focusStat span{display:block;font-size:7px;color:#6d98a9;letter-spacing:.08em}.focusStat b{display:block;font-size:22px;color:#54e7ff;margin-top:8px}.focusStat small{display:block;color:#577f8f;font-size:6px;margin-top:3px}.settingsGrid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.settingBox{border:1px solid #0b4e63;background:#07131c;padding:13px}.settingBox b{font-size:9px}.settingBox small{display:block;font-size:7px;color:#6f98a8;margin-top:5px;line-height:1.55}.settingBox button{margin-top:10px;border:1px solid #12bddd;background:#0a2a37;color:#aeefff;padding:8px 11px;font-size:8px;cursor:pointer}.settingBox button:hover{background:#0c3a4b}.viewTransition{animation:viewIn .22s ease both}@keyframes viewIn{from{opacity:.25;transform:translateY(5px)}to{opacity:1;transform:none}}@media(max-width:900px){.focusGrid{grid-template-columns:repeat(2,1fr)}.settingsGrid{grid-template-columns:1fr}.viewContext{align-items:flex-start;flex-direction:column}}`;document.head.appendChild(style)}
function ensureContext(){let el=document.getElementById('viewContext');if(el)return el;el=document.createElement('section');el.id='viewContext';el.className='viewContext hud';document.querySelector('.content').prepend(el);return el}
function ensureFocus(){let el=document.getElementById('focusView');if(el)return el;el=document.createElement('section');el.id='focusView';el.className='focusPanel hud';const feed=document.querySelector('.feed');document.querySelector('.content').insertBefore(el,feed);return el}
function resetLayout(){const fleet=document.querySelector('.fleetWrap'),mid=document.querySelector('.mid'),bottom=document.querySelector('.bottom'),feed=document.querySelector('.feed');[fleet,mid,bottom,feed].forEach(x=>{if(x){x.style.display='';x.classList.remove('viewTransition')}});[...mid.children].forEach(x=>x.style.display='');[...bottom.children].forEach(x=>x.style.display='');mid.style.gridTemplateColumns='';bottom.style.gridTemplateColumns='';fleet.style.gridTemplateColumns='';const focus=ensureFocus();focus.style.display='none';focus.innerHTML=''}
function onlyChildren(parent,indices){[...parent.children].forEach((el,i)=>el.style.display=indices.includes(i)?'':'none');parent.style.gridTemplateColumns=indices.length>1?`repeat(${indices.length},minmax(0,1fr))`:'1fr';parent.classList.add('viewTransition')}
function reportMarkup(){const s=state.summary||{};const certDays=state.checks.map(c=>c.certificate?.daysRemaining).filter(Number.isFinite);const minCert=certDays.length?Math.min(...certDays):'--';return `<div class="panelHead"><b>LATEST SENTINEL REPORT</b><span>${state.generatedAt?new Date(state.generatedAt).toLocaleString():'WAITING FOR SCAN'}</span></div><div class="focusGrid"><div class="focusStat"><span>FLEET HEALTH</span><b>${s.avgHealth??'--'}%</b><small>${s.online??0}/${s.total??4} endpoints online</small></div><div class="focusStat"><span>SECURITY COVERAGE</span><b>${s.avgSecurity??'--'}%</b><small>${s.securityGaps??'--'} baseline gaps</small></div><div class="focusStat"><span>AVG RESPONSE</span><b>${s.avgResponseMs??'--'}ms</b><small>Current sensor sweep</small></div><div class="focusStat"><span>SHORTEST TLS WINDOW</span><b>${minCert}${minCert==='--'?'':'d'}</b><small>Certificate days remaining</small></div></div><div style="margin-top:12px;font-size:7px;color:#688f9f;line-height:1.7">Report source: ${esc(state.source||'not connected')} · Generated directly from live Sentinel checks. No simulated operational values are included.</div>`}
function settingsMarkup(){return `<div class="panelHead"><b>MONITOR CONFIGURATION</b><span>TRUTH MODE ENABLED</span></div><div class="settingsGrid"><div class="settingBox"><b>SENSOR CYCLE</b><small>Automatic external scan every 60 seconds. It measures endpoint reachability, latency, security headers, robots.txt, sitemap.xml and TLS certificate state.</small><button id="manualScanBtn">RUN SENSOR SWEEP NOW</button></div><div class="settingBox"><b>CONNECTED FLEET</b><small>${SITES.map(s=>`${s.name} · ${s.url}`).join('<br>')}</small></div><div class="settingBox"><b>LOCAL HISTORY</b><small>Response-time samples are retained in this browser for the animated telemetry graphs. Current limit: 30 samples per platform.</small></div><div class="settingBox"><b>DATA POLICY</b><small>If a sensor is not connected, Sentinel must display NOT CONNECTED or unavailable. It must never manufacture operational data to fill a panel.</small></div></div>`}
function applyView(key,scroll=true){activeView=NAV_KEYS.includes(key)?key:'overview';installNavigationStyles();resetLayout();const context=ensureContext(),focus=ensureFocus(),fleet=document.querySelector('.fleetWrap'),mid=document.querySelector('.mid'),bottom=document.querySelector('.bottom');document.querySelectorAll('#nav button').forEach((b,i)=>b.classList.toggle('active',NAV_KEYS[i]===activeView));if(activeView==='overview'){context.classList.remove('show');if(scroll)window.scrollTo({top:0,behavior:'smooth'});return}const meta=VIEW_META[activeView];context.classList.add('show');context.innerHTML=`<div><div class="vcK">ADA SENTINEL / ${meta[0]}</div><h2>${meta[0]}</h2></div><p>${meta[1]}</p><div class="vcLive">LIVE SENSOR DATA</div>`;fleet.style.display='none';mid.style.display='none';bottom.style.display='none';if(activeView==='websites'){fleet.style.display='grid';fleet.style.gridTemplateColumns='1fr';fleet.classList.add('viewTransition')}if(activeView==='security'){mid.style.display='grid';bottom.style.display='grid';onlyChildren(mid,[1]);onlyChildren(bottom,[3])}if(activeView==='monitoring'){mid.style.display='grid';bottom.style.display='grid';onlyChildren(mid,[2]);onlyChildren(bottom,[2])}if(activeView==='deployments'){bottom.style.display='grid';onlyChildren(bottom,[0])}if(activeView==='errors'){mid.style.display='grid';bottom.style.display='grid';onlyChildren(mid,[0]);onlyChildren(bottom,[1])}if(activeView==='reports'){focus.style.display='block';focus.innerHTML=reportMarkup();focus.classList.add('viewTransition')}if(activeView==='settings'){focus.style.display='block';focus.innerHTML=settingsMarkup();focus.classList.add('viewTransition');setTimeout(()=>document.getElementById('manualScanBtn')?.addEventListener('click',scan),0)}if(scroll)document.querySelector('.main')?.scrollIntoView({behavior:'smooth',block:'start'})}
function wireNavigation(){installNavigationStyles();ensureContext();ensureFocus();document.querySelectorAll('#nav button').forEach((button,i)=>{button.dataset.view=NAV_KEYS[i]||'overview';button.addEventListener('click',()=>applyView(button.dataset.view,true))})}
wireNavigation();applyView('overview',false);
scan();setInterval(scan,60000);